development:
  clients:
    default:
      database: puma_rack_app
      hosts:
        - localhost:27017
      options:
        user: 'root'
        password: 'example'
        auth_source: admin
production:
  clients:
    default:
      database: puma_rack_app
      hosts:
        - mongo-db:27017
      options:
        user: 'root'
        password: 'example'
        auth_source: admin